version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-app
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:xvo86zKpOFgR3sIt96isd8aqT3aCqITH3KR2O3s3DwA=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: book-app-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretRootPassword
      MYSQL_DATABASE: last6
      MYSQL_USER: book_app_user
      MYSQL_PASSWORD: UserSecretPassword
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: book-app-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: SuperSecretRootPassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
